import type { Workflow, FallbackGuide, DrillRecord, Policy, ComplianceEvaluation } from "./types";

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const seedWorkflows: Workflow[] = [
  {
    id: "wf-1",
    name: "Monthly Vendor Invoice Processing",
    department: "Finance",
    aiTool: "Zapier + GPT-4o",
    frequency: "Monthly",
    classification: "Confidential",
    taskDescription:
      "AI ingests incoming vendor invoices from the shared mailbox, extracts line items, matches them against open purchase orders in the ERP, flags discrepancies, and routes approved invoices to the payments queue.",
    expectedOutput: "Approved invoices list sent to finance team and queued for payment",
    systems: [
      { systemName: "NetSuite ERP", action: "Write", dataType: "Invoice records" },
      { systemName: "Outlook Mailbox", action: "Read", dataType: "Email attachments" },
    ],
    decisions: [
      { decisionPoint: "Invoice vs PO mismatch", options: "Approve / Hold / Reject", chosen: "Hold", reason: "Variance over 5% requires human review" },
    ],
    data: [{ source: "Vendor Invoices", type: "Financial", volume: "~400/month" }],
    approvalsSkipped: true,
    skippedWhich: "Secondary controller sign-off",
    skippedReason: "AI auto-approved invoices under $1,000 threshold",
    skippedRisk: "high",
    resilienceScore: 38,
    lastUpdated: daysAgo(3),
    lastHumanTouch: daysAgo(42),
    hasGuide: true,
  },
  {
    id: "wf-2",
    name: "Customer Onboarding Sequence",
    department: "Customer Success",
    aiTool: "Internal CS Bot",
    frequency: "Daily",
    classification: "Internal",
    taskDescription:
      "Bot provisions accounts, sends welcome sequences, schedules kickoff calls, and assigns CSMs based on account tier.",
    expectedOutput: "Fully provisioned customer account with kickoff scheduled",
    systems: [
      { systemName: "Salesforce", action: "Write", dataType: "Account records" },
      { systemName: "Calendly", action: "Notify", dataType: "Scheduling" },
    ],
    decisions: [
      { decisionPoint: "CSM assignment", options: "Tier A / Tier B / Pool", chosen: "Tier-based", reason: "ARR thresholds" },
    ],
    data: [{ source: "CRM Records", type: "PII", volume: "~30/day" }],
    approvalsSkipped: false,
    resilienceScore: 72,
    lastUpdated: daysAgo(1),
    lastHumanTouch: daysAgo(8),
    hasGuide: true,
  },
  {
    id: "wf-3",
    name: "Procurement Vendor Approval",
    department: "Procurement",
    aiTool: "Procurement Bot",
    frequency: "Weekly",
    classification: "Restricted",
    taskDescription:
      "Evaluates new vendor applications, runs compliance and sanctions checks, scores risk, and approves vendors under threshold automatically.",
    expectedOutput: "Approved vendor list with compliance attestation",
    systems: [
      { systemName: "Coupa", action: "Approve", dataType: "Vendor master" },
      { systemName: "Sanctions API", action: "Read", dataType: "Compliance" },
    ],
    decisions: [
      { decisionPoint: "Risk threshold", options: "Auto-approve / Escalate", chosen: "Auto-approve <medium", reason: "Speed of onboarding" },
    ],
    data: [{ source: "Vendor Master", type: "Operational", volume: "~15/week" }],
    approvalsSkipped: true,
    skippedWhich: "Legal review for restricted categories",
    skippedReason: "Throughput pressure",
    skippedRisk: "critical",
    resilienceScore: 24,
    lastUpdated: daysAgo(5),
    lastHumanTouch: daysAgo(67),
    hasGuide: false,
  },
  {
    id: "wf-4",
    name: "Payroll Anomaly Detection",
    department: "HR",
    aiTool: "GPT-4o Classifier",
    frequency: "Monthly",
    classification: "Restricted",
    taskDescription: "Scans payroll runs for anomalies, duplicate payments, and ghost employees before disbursement.",
    expectedOutput: "Anomaly report cleared for payroll release",
    systems: [{ systemName: "Workday", action: "Read", dataType: "Payroll" }],
    decisions: [{ decisionPoint: "Anomaly flag", options: "Hold / Release", chosen: "Hold >2σ", reason: "Risk control" }],
    data: [{ source: "Payroll Ledger", type: "PII", volume: "~1,200 records" }],
    approvalsSkipped: false,
    resilienceScore: 55,
    lastUpdated: daysAgo(10),
    lastHumanTouch: daysAgo(19),
    hasGuide: false,
  },
  {
    id: "wf-5",
    name: "Support Ticket Triage",
    department: "Customer Success",
    aiTool: "Zendesk AI",
    frequency: "Daily",
    classification: "Internal",
    taskDescription: "Classifies, prioritises, and routes inbound support tickets; auto-resolves common requests.",
    expectedOutput: "Triaged ticket queue with priority labels",
    systems: [{ systemName: "Zendesk", action: "Write", dataType: "Tickets" }],
    decisions: [{ decisionPoint: "Auto-resolve", options: "Resolve / Route", chosen: "Resolve known", reason: "Deflection" }],
    data: [{ source: "Support Tickets", type: "Operational", volume: "~500/day" }],
    approvalsSkipped: false,
    resilienceScore: 81,
    lastUpdated: daysAgo(1),
    lastHumanTouch: daysAgo(4),
    hasGuide: true,
  },
  {
    id: "wf-6",
    name: "Contract Clause Review",
    department: "Legal",
    aiTool: "Internal Legal LLM",
    frequency: "Weekly",
    classification: "Confidential",
    taskDescription: "Reviews incoming contracts against the clause playbook and flags non-standard terms.",
    expectedOutput: "Redlined contract with risk-flagged clauses",
    systems: [{ systemName: "Ironclad", action: "Write", dataType: "Contracts" }],
    decisions: [{ decisionPoint: "Clause acceptance", options: "Accept / Flag", chosen: "Flag non-standard", reason: "Risk" }],
    data: [{ source: "Contract Repository", type: "Operational", volume: "~25/week" }],
    approvalsSkipped: false,
    resilienceScore: 47,
    lastUpdated: daysAgo(14),
    lastHumanTouch: daysAgo(31),
    hasGuide: false,
  },
  {
    id: "wf-7",
    name: "IT Access Provisioning",
    department: "IT",
    aiTool: "Okta Workflows + GPT",
    frequency: "Daily",
    classification: "Restricted",
    taskDescription: "Grants and revokes system access based on role changes and HR triggers.",
    expectedOutput: "Provisioned access aligned to least-privilege policy",
    systems: [{ systemName: "Okta", action: "Approve", dataType: "Identity" }],
    decisions: [{ decisionPoint: "Privilege grant", options: "Grant / Deny", chosen: "Role-based", reason: "RBAC" }],
    data: [{ source: "Identity Directory", type: "PII", volume: "~40/day" }],
    approvalsSkipped: true,
    skippedWhich: "Manager confirmation",
    skippedReason: "Auto-grant for standard roles",
    skippedRisk: "high",
    resilienceScore: 33,
    lastUpdated: daysAgo(2),
    lastHumanTouch: daysAgo(73),
    hasGuide: false,
  },
  {
    id: "wf-8",
    name: "Demand Forecasting",
    department: "Operations",
    aiTool: "Forecast Engine",
    frequency: "Weekly",
    classification: "Internal",
    taskDescription: "Generates weekly demand forecasts feeding the replenishment system.",
    expectedOutput: "Approved demand plan pushed to supply chain",
    systems: [{ systemName: "SAP IBP", action: "Write", dataType: "Forecasts" }],
    decisions: [{ decisionPoint: "Forecast override", options: "Accept / Adjust", chosen: "Accept", reason: "Model trust" }],
    data: [{ source: "Sales History", type: "Operational", volume: "~2yr history" }],
    approvalsSkipped: false,
    resilienceScore: 64,
    lastUpdated: daysAgo(6),
    lastHumanTouch: daysAgo(12),
    hasGuide: false,
  },
];

export const seedGuides: FallbackGuide[] = [
  {
    id: "gd-1",
    workflowId: "wf-1",
    workflowName: "Monthly Vendor Invoice Processing",
    guide_title: "Manual Vendor Invoice Processing — Human Fallback",
    estimated_time_manual: "3–4 hours per batch",
    required_personnel: ["Accounts Payable Clerk", "Finance Controller"],
    required_system_access: ["NetSuite ERP", "Shared Finance Mailbox"],
    pre_conditions: ["Access to open PO list", "Vendor master is current"],
    steps: [
      {
        step_number: 1,
        title: "Collect incoming invoices",
        detailed_instruction: "Open the shared finance mailbox and export all invoice attachments received since the last run into the AP working folder.",
        system_used: "Outlook Mailbox",
        decision_points: ["If an invoice is missing a PO number, set aside for vendor follow-up"],
        common_mistakes: ["Skipping invoices in spam/quarantine"],
      },
      {
        step_number: 2,
        title: "Match invoices to purchase orders",
        detailed_instruction: "For each invoice, locate the matching open PO in NetSuite and verify quantities and unit pricing.",
        system_used: "NetSuite ERP",
        decision_points: ["Variance over 5% → hold and notify controller"],
        common_mistakes: ["Approving partial deliveries as complete"],
      },
      {
        step_number: 3,
        title: "Route for approval and payment",
        detailed_instruction: "Compile the approved invoice list and submit to the payments queue with controller sign-off.",
        system_used: "NetSuite ERP",
        decision_points: ["Invoices over $1,000 require dual sign-off"],
        common_mistakes: ["Releasing without secondary controller approval"],
      },
    ],
    escalation_path: "Contact the Finance Controller; for ERP issues escalate to IT Service Desk (ext. 4400).",
    estimated_risk_if_skipped: "Delayed vendor payments risk late fees and supply disruption; unmatched invoices create audit exposure.",
    generatedDate: daysAgo(20),
    lastReviewed: daysAgo(40),
  },
  {
    id: "gd-2",
    workflowId: "wf-2",
    workflowName: "Customer Onboarding Sequence",
    guide_title: "Manual Customer Onboarding — Human Fallback",
    estimated_time_manual: "45–60 minutes per account",
    required_personnel: ["Customer Success Manager"],
    required_system_access: ["Salesforce", "Email"],
    pre_conditions: ["Signed contract on file"],
    steps: [
      {
        step_number: 1,
        title: "Provision the account",
        detailed_instruction: "Create the customer account record in Salesforce with the correct tier and entitlements.",
        system_used: "Salesforce",
        decision_points: ["Tier A → assign senior CSM"],
        common_mistakes: ["Wrong tier assignment"],
      },
      {
        step_number: 2,
        title: "Send welcome and schedule kickoff",
        detailed_instruction: "Send the welcome email template and propose three kickoff slots.",
        system_used: "Email",
        decision_points: ["Enterprise accounts → schedule within 48h"],
        common_mistakes: ["Forgetting to CC the account exec"],
      },
    ],
    escalation_path: "Escalate to CS Team Lead for tier disputes.",
    estimated_risk_if_skipped: "Poor first impression and delayed time-to-value, increasing early churn risk.",
    generatedDate: daysAgo(6),
    lastReviewed: daysAgo(6),
  },
  {
    id: "gd-3",
    workflowId: "wf-5",
    workflowName: "Support Ticket Triage",
    guide_title: "Manual Support Triage — Human Fallback",
    estimated_time_manual: "Ongoing — ~2 min per ticket",
    required_personnel: ["Support Agent", "Support Lead"],
    required_system_access: ["Zendesk"],
    pre_conditions: ["Access to triage macros"],
    steps: [
      {
        step_number: 1,
        title: "Review the inbound queue",
        detailed_instruction: "Sort the unassigned queue by SLA risk and read each ticket subject.",
        system_used: "Zendesk",
        decision_points: ["P1 outage keywords → escalate immediately"],
        common_mistakes: ["Ignoring SLA timers"],
      },
      {
        step_number: 2,
        title: "Classify and route",
        detailed_instruction: "Apply the correct priority and route to the owning team using the routing matrix.",
        system_used: "Zendesk",
        decision_points: ["Billing issues → Finance support"],
        common_mistakes: ["Mis-routing to the wrong team"],
      },
    ],
    escalation_path: "Support Lead handles P1 incidents and capacity overflow.",
    estimated_risk_if_skipped: "SLA breaches, customer dissatisfaction, and backlog accumulation.",
    generatedDate: daysAgo(2),
  },
];

export const seedDrills: DrillRecord[] = [
  {
    id: "dr-1",
    name: "Procurement Bot Outage Drill",
    dateRun: daysAgo(9),
    agent: "Procurement Bot",
    team: "Procurement Operations",
    outageDuration: "3 days",
    mode: "Tabletop Exercise",
    readinessScore: 68,
    grade: "C",
    passed: false,
    scenario: {
      scenario_title: "Procurement Bot Goes Dark",
      scenario_briefing: "At 06:00 the procurement automation stops responding...",
      critical_question: "Can your team approve urgent vendor payments without the bot for 3 days?",
      drill_tasks: [],
      scoring_criteria: [],
      total_points_available: 100,
    },
    completedTasks: [],
    debrief: "Team located the fallback guide but lacked Coupa approval rights. Recommend cross-training two backups.",
  },
  {
    id: "dr-2",
    name: "Invoice AI Failure Drill",
    dateRun: daysAgo(25),
    agent: "Zapier + GPT-4o",
    team: "Accounts Payable",
    outageDuration: "1 day",
    mode: "Live Checklist",
    readinessScore: 91,
    grade: "A",
    passed: true,
    scenario: {
      scenario_title: "Invoice Automation Down",
      scenario_briefing: "The invoice pipeline has failed mid-cycle...",
      critical_question: "Can AP close the month manually?",
      drill_tasks: [],
      scoring_criteria: [],
      total_points_available: 100,
    },
    completedTasks: [],
    debrief: "Strong manual recovery. AP closed within SLA. Document the export shortcut for future runs.",
  },
];

export const seedPolicies: Policy[] = [
  {
    id: "pol-1",
    name: "Data Protection & PII Handling Policy",
    category: "Data Privacy",
    source: "upload",
    content:
      "All workflows that process personally identifiable information (PII) must: 1) Restrict access to PII on a need-to-know basis. 2) Never transmit PII over unencrypted channels or personal email accounts. 3) Maintain an audit trail of every read/write to PII records. 4) Require human approval before any automated deletion of customer records. 5) Ensure any AI/third-party tool processing PII has a signed data processing agreement. 6) Retain PII no longer than required by law and document the retention period.",
    summary:
      "Requires need-to-know access, encryption, audit trails, human approval for deletions, signed DPAs for AI tools, and documented retention for any workflow handling PII.",
    addedDate: daysAgo(40),
  },
  {
    id: "pol-2",
    name: "Financial Controls & Segregation of Duties",
    category: "Finance",
    source: "upload",
    content:
      "Financial workflows must enforce segregation of duties: the entity that initiates a payment cannot also approve it. All payments above the materiality threshold require a documented human approval. Automated invoice matching must flag, not auto-approve, any discrepancy above tolerance. A complete reconciliation must be retained for every close. No approval step may be skipped without a documented, time-limited exception signed by the Finance lead.",
    summary:
      "Mandates segregation of duties, human approval above thresholds, flagging of discrepancies, retained reconciliations, and documented exceptions for skipped approvals.",
    addedDate: daysAgo(25),
  },
];

export const seedEvaluations: ComplianceEvaluation[] = [];
