/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRecorderRouteImport } from './routes/workflow-recorder'
import { Route as FallbackGuidesRouteImport } from './routes/fallback-guides'
import { Route as DependencyMapRouteImport } from './routes/dependency-map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiClaudeRouteImport } from './routes/api/claude'

const WorkflowRecorderRoute = WorkflowRecorderRouteImport.update({
  id: '/workflow-recorder',
  path: '/workflow-recorder',
  getParentRoute: () => rootRouteImport,
} as any)
const FallbackGuidesRoute = FallbackGuidesRouteImport.update({
  id: '/fallback-guides',
  path: '/fallback-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DependencyMapRoute = DependencyMapRouteImport.update({
  id: '/dependency-map',
  path: '/dependency-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeRoute = ApiClaudeRouteImport.update({
  id: '/api/claude',
  path: '/api/claude',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dependency-map': typeof DependencyMapRoute
  '/fallback-guides': typeof FallbackGuidesRoute
  '/workflow-recorder': typeof WorkflowRecorderRoute
  '/api/claude': typeof ApiClaudeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dependency-map': typeof DependencyMapRoute
  '/fallback-guides': typeof FallbackGuidesRoute
  '/workflow-recorder': typeof WorkflowRecorderRoute
  '/api/claude': typeof ApiClaudeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dependency-map': typeof DependencyMapRoute
  '/fallback-guides': typeof FallbackGuidesRoute
  '/workflow-recorder': typeof WorkflowRecorderRoute
  '/api/claude': typeof ApiClaudeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dependency-map'
    | '/fallback-guides'
    | '/workflow-recorder'
    | '/api/claude'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dependency-map'
    | '/fallback-guides'
    | '/workflow-recorder'
    | '/api/claude'
  id:
    | '__root__'
    | '/'
    | '/dependency-map'
    | '/fallback-guides'
    | '/workflow-recorder'
    | '/api/claude'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DependencyMapRoute: typeof DependencyMapRoute
  FallbackGuidesRoute: typeof FallbackGuidesRoute
  WorkflowRecorderRoute: typeof WorkflowRecorderRoute
  ApiClaudeRoute: typeof ApiClaudeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow-recorder': {
      id: '/workflow-recorder'
      path: '/workflow-recorder'
      fullPath: '/workflow-recorder'
      preLoaderRoute: typeof WorkflowRecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallback-guides': {
      id: '/fallback-guides'
      path: '/fallback-guides'
      fullPath: '/fallback-guides'
      preLoaderRoute: typeof FallbackGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependency-map': {
      id: '/dependency-map'
      path: '/dependency-map'
      fullPath: '/dependency-map'
      preLoaderRoute: typeof DependencyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude': {
      id: '/api/claude'
      path: '/api/claude'
      fullPath: '/api/claude'
      preLoaderRoute: typeof ApiClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DependencyMapRoute: DependencyMapRoute,
  FallbackGuidesRoute: FallbackGuidesRoute,
  WorkflowRecorderRoute: WorkflowRecorderRoute,
  ApiClaudeRoute: ApiClaudeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
